AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TaxFlowAI Backend - Production Ready

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
  
  DatabaseUrl:
    Type: String
    NoEcho: true
    Description: PostgreSQL connection string
  
  SupabaseUrl:
    Type: String
    Description: Supabase project URL
  
  SupabaseServiceKey:
    Type: String
    NoEcho: true
    Description: Supabase service role key
  
  OpenAIKey:
    Type: String
    NoEcho: true
    Description: OpenAI API key
  
  JwtSecret:
    Type: String
    NoEcho: true
    Description: JWT signing secret
  
  AllowedOrigin:
    Type: String
    Default: "*"
    Description: CORS allowed origin


Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 1024
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        DATABASE_URL: !Ref DatabaseUrl
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey
        OPENAI_API_KEY: !Ref OpenAIKey
        JWT_SECRET: !Ref JwtSecret
        ALLOWED_ORIGIN: !Ref AllowedOrigin
        SES_EMAIL: notifications@isaloumapps.com
        LOGIN_URL: https://www.isaloumapps.com/login
        APP_NAME: TaxFlowAI
  
Resources:
  # DynamoDB - defined first so Lambda functions can reference it
  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST  # Serverless pricing - only pay for what you use
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: production
        - Key: Application
          Value: taxflowai

  # API Gateway
  TaxFlowAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      BinaryMediaTypes:
        - 'multipart/form-data'
        - '*~1*'
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Auth Lambda
  AuthFunction:
    Description: Authentication and user management - Updated Feb 13 2026
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambda/auth.handler
      Runtime: nodejs20.x
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          JWT_SECRET: !Ref JwtSecret
          JWT_EXPIRES_IN: '24h'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UsersTable.Arn
      Events:
        AuthProxy:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /auth/{proxy+}
            Method: ANY
        AuthRoot:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /auth
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: 'es2020'
        Sourcemap: false
        EntryPoints:
          - src/lambda/auth.ts
        External:
          - sharp
          - '@mapbox/node-pre-gyp'
          - mock-aws-s3
          - aws-sdk
          - nock
          - tesseract.js
          - '@google-cloud/vision'
          - '@prisma/client'

  # Documents Lambda
  DocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambda/documents.handler
      Events:
        DocumentsProxy:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /documents/{proxy+}
            Method: ANY
        DocumentsRoot:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /documents
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: 'es2020'
        Sourcemap: false
        EntryPoints:
          - src/lambda/documents.ts
        External:
          - sharp
          - '@mapbox/node-pre-gyp'
          - mock-aws-s3
          - aws-sdk
          - nock
          - tesseract.js
          - '@google-cloud/vision'
          - '@prisma/client'

  # Users Lambda
  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambda/users.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        UsersProxy:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /users/{proxy+}
            Method: ANY
        UsersRoot:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /users
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: 'es2020'
        Sourcemap: false
        EntryPoints:
          - src/lambda/users.ts
        External:
          - sharp
          - '@mapbox/node-pre-gyp'
          - mock-aws-s3
          - aws-sdk
          - nock
          - tesseract.js
          - '@google-cloud/vision'
          - '@prisma/client'

  # Notifications Lambda
  NotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambda/notifications.handler
      Events:
        NotificationsProxy:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /notifications/{proxy+}
            Method: ANY
        NotificationsRoot:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /notifications
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: 'es2020'
        Sourcemap: false
        EntryPoints:
          - src/lambda/notifications.ts
        External:
          - sharp
          - '@mapbox/node-pre-gyp'
          - mock-aws-s3
          - aws-sdk
          - nock
          - tesseract.js
          - '@google-cloud/vision'
          - '@prisma/client'

  # CloudWatch Log Groups
  AuthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AuthFunction}
      RetentionInDays: 7

  DocumentsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DocumentsFunction}
      RetentionInDays: 7

  UsersFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${UsersFunction}
      RetentionInDays: 7

  NotificationsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${NotificationsFunction}
      RetentionInDays: 7

  # Health Check Lambda
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambda/health.handler
      Events:
        HealthProxy:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /health/{proxy+}
            Method: ANY
        HealthRoot:
          Type: Api
          Properties:
            RestApiId: !Ref TaxFlowAPI
            Path: /health
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: 'es2020'
        Sourcemap: false
        EntryPoints:
          - src/lambda/health.ts
        External:
          - sharp
          - '@mapbox/node-pre-gyp'
          - mock-aws-s3
          - aws-sdk
          - nock
          - tesseract.js
          - '@google-cloud/vision'
          - '@prisma/client'

  HealthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HealthFunction}
      RetentionInDays: 7

  # DynamoDB Table for Users
Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${TaxFlowAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"
  
  AuthFunctionArn:
    Description: Auth Lambda ARN
    Value: !GetAtt AuthFunction.Arn
  
  DocumentsFunctionArn:
    Description: Documents Lambda ARN
    Value: !GetAtt DocumentsFunction.Arn
  
  UsersFunctionArn:
    Description: Users Lambda ARN
    Value: !GetAtt UsersFunction.Arn
  
  NotificationsFunctionArn:
    Description: Notifications Lambda ARN
    Value: !GetAtt NotificationsFunction.Arn

  HealthFunctionArn:
    Description: Health Lambda ARN
    Value: !GetAtt HealthFunction.Arn
